#!/usr/bin/env python3
"""Check the structural hypotheses of Theorem 7.1 on the released data of the earlier report
(Mghirbi and Douglas, Zenodo, doi:10.5281/zenodo.23093839).

Standard library only.  Inputs, in earlier/:
  presentation.json            the 43-generator presentation (4417 relators)
  original_channel.json.gz     the fully referenced channel with all 16428 prefix triangles,
                               as regenerated by the earlier report's rebuild_all.py
  fifteen_qubits_channel.json.gz, deletion_certificates.json   as released with the earlier report

Checks:
  * the original channel is the baseline that the released files name (SHA-256 of its
    uncompressed bytes);
  * every relator, read letter by letter, follows prefix triangles of the original table and
    returns to the identity; relators have length at most 19;
  * the released fifteen-qubit channel keeps exactly the retained original triangles, in order;
  * every deleted triangle is either (z, y', x) with (x, y, z) retained and the protected inverse
    triangle of y retained in one of its two orientations, or a reversed protected inverse;
  * all 43 protected inverse triangles are retained;
  * the singletons are the identity (787 positions) and the witness label (one position);
  * every non-identity label occurs in a retained triangle.
"""
import gzip
import hashlib
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'earlier')


def check(cond, msg):
    if not cond:
        raise RuntimeError(msg)


pres = json.load(open(os.path.join(ROOT, 'presentation.json')))
from datafile import read_data
raw = read_data(os.path.join(ROOT, 'original_channel.json.gz'))
orig = json.loads(raw)
phi15 = json.loads(read_data(os.path.join(ROOT, 'fifteen_qubits_channel.json.gz')))
dele = json.load(open(os.path.join(ROOT, 'deletion_certificates.json')))

base = hashlib.sha256(raw).hexdigest()
check(base == phi15['baseline_uncompressed_sha256'] == dele['baseline_sha256'], 'baseline hash mismatch')

T0 = [tuple(t) for t in orig['triangles']]
check(len(T0) == 16428 == dele['original_triangle_count'], 'original triangle count')
table = {}
for x, y, z in T0:
    check((x, y) not in table or table[x, y] == z, 'inconsistent original table')
    table[x, y] = z

label = {s: g for s, g in orig['generator_labels']}
check(label == {s: g for s, g in phi15['generator_labels']}, 'generator labels differ')
check(len(label) == 86, 'signed generator count')
check(label[43] == 85 and pres['witness_generator'] == 43, 'the witness generator 43 has label 85')

# Relator walks.
rels = pres['relators']
check(len(rels) == 4417, 'relator count')
words = [tuple(r['word']) for r in rels]
check(len(set(words)) == 4417 and sum(map(len, words)) == 41953, 'distinct relators, total length 41953')
check(all(w[i] != -w[i + 1] for w in words for i in range(len(w) - 1)), 'relators are freely reduced')
maxlen = 0
needed = set()
for rel in rels:
    w = rel['word']
    maxlen = max(maxlen, len(w))
    cur = label[w[0]]
    for s in w[1:]:
        y = label[s]
        check(cur != 0, f'relator {w} has a proper prefix equal to the identity')
        check((cur, y) in table, f'missing prefix triangle in relator {w}')
        needed.add((cur, y, table[cur, y]))
        cur = table[cur, y]
    check(cur == 0, f'relator {w} does not return to the identity')
check(maxlen <= 19, 'relator length')
# The table is exactly the prefix triangles of the relators and the 43 inverse triangles.
needed |= {(label[s], label[-s], 0) for s in range(1, 44)}
check(set(T0) == needed, 'original table is not exactly the prefix and inverse triangles')
# The fully referenced channel: one singleton for each of its 11230 labels.
check(orig['kraus_rank'] == len(orig['kraus']) == 11230, 'fully referenced channel: label count')
check(orig['dimension'] == 2 * len(T0) + 11230 == 44086, 'fully referenced channel: dimension')
full_single = [sum(1 for r, c, n in E if r == c and n == 5) for E in orig['kraus']]
check(all(k == 1 for k in full_single), 'fully referenced channel: one singleton per label')
fent = [set(map(tuple, E)) for E in orig['kraus']]
check(all((g, g, 5) in fent[g] for g in range(11230)), 'fully referenced channel: singleton of label g at position g')
for n, (x, y, z) in enumerate(T0):
    p = 11230 + 2 * n
    check((p, p, 3) in fent[0] and (p, p + 1, 4) in fent[y] and (p + 1, p, 4) in fent[x]
          and (p + 1, p + 1, -3) in fent[z], f'fully referenced channel: block pattern of triangle {n}')
check(sum(map(len, fent)) == 76942 == 11230 + 4 * len(T0), 'fully referenced channel: 76942 entries')

# Retained triangles.
keep = dele['retained_original_indices']
check(len(keep) == 15990, 'retained count')
T15 = [tuple(t) for t in phi15['triangles']]
check(T15 == [T0[i] for i in keep], 'released triangles are not the retained original triangles')
R = set(T15)
deleted = [T0[i] for i in range(len(T0)) if i not in set(keep)]
check(len(deleted) == 438, 'deleted count')

inv = {label[s]: label[-s] for s in label}
F = {(label[s], label[-s], 0) for s in range(1, 44)}
check(len(F) == 43 and F <= R, 'protected inverse triangles not all retained')

fam_a = fam_b = both = only_rev = 0
for (u, w, v) in deleted:
    if v == 0 and (w, u, 0) in F and (w, u, 0) in R:
        fam_b += 1
        continue
    check(w in inv, f'deleted triangle {(u, w, v)} has no letter in the middle')
    y = inv[w]
    check((v, y, u) in R, f'deleted triangle {(u, w, v)} has no retained partner')
    fwd, rev = (y, w, 0) in R, (w, y, 0) in R
    check(fwd or rev, f'deleted triangle {(u, w, v)} has no retained protected inverse')
    fam_a += 1
    if fwd:
        both += 1
    else:
        only_rev += 1
check((fam_a, fam_b) == (408, 30), f'deletion families {(fam_a, fam_b)}')

# Singletons: entries of value 5 (=1) on the diagonal outside triangle blocks.
tri_pos = set()
nanch = phi15['dimension'] - 2 * len(T15)
single = {}
for g, E in enumerate(phi15['kraus']):
    for r, c, n in E:
        if r == c and n == 5:
            single.setdefault(g, []).append(r)
check(sorted(single) == [0, 85], f'singleton labels {sorted(single)}')
check(len(single[0]) == 787 and len(single[85]) == 1, 'singleton multiplicities')
check(len(single[0]) + len(single[85]) == nanch, 'singleton count vs dimension')

# Label coverage by retained triangles.
covered = set()
for t in T15:
    covered.update(t)
check(covered | {0} == set(range(phi15['kraus_rank'])), 'label coverage')

# Kraus block pattern of Definition 3.1 and exact normalization (denominator 5),
# for each reduced channel: Phi_15, Phi_2 (no padding), Phi_1 (identity singleton only).
from collections import defaultdict


def check_reduced(o, name, lead, pad_count):
    """lead: labels of the leading singleton positions 0, 1, ...; then triangles; then padding."""
    check([tuple(t) for t in o['triangles']] == T15, f'{name}: triangles differ from the retained table')
    check(o['baseline_uncompressed_sha256'] == base, f'{name}: baseline hash')
    D = o['dimension']
    K = o['kraus']
    ent = [set(map(tuple, E)) for E in K]
    for pos, g in enumerate(lead):
        check((pos, pos, 5) in ent[g], f'{name}: singleton {g} at {pos}')
    t0 = len(lead)
    for n, (x, y, z) in enumerate(T15):
        p = t0 + 2 * n
        check((p, p, 3) in ent[0] and (p, p + 1, 4) in ent[y] and (p + 1, p, 4) in ent[x]
              and (p + 1, p + 1, -3) in ent[z], f'{name}: block pattern of triangle {n}')
    pad = list(range(t0 + 2 * len(T15), D))
    check(len(pad) == pad_count and all((p, p, 5) in ent[0] for p in pad), f'{name}: padding')
    sing = sorted(g for g, E in enumerate(K) for (r, c, v) in E if r == c and v == 5)
    check(sing.count(0) == 1 + pad_count and len(sing) == len(lead) + pad_count, f'{name}: singleton count')
    seen = set()
    left = defaultdict(int)
    right = defaultdict(int)
    for E in K:
        rows = defaultdict(list)
        cols = defaultdict(list)
        for r, c, v in E:
            check((r, c) not in seen, f'{name}: overlapping Kraus supports')
            seen.add((r, c))
            rows[r].append((c, v))
            cols[c].append((r, v))
        for vals in rows.values():
            for c1, n1 in vals:
                for c2, n2 in vals:
                    left[c1, c2] += n1 * n2
        for vals in cols.values():
            for r1, n1 in vals:
                for r2, n2 in vals:
                    right[r1, r2] += n1 * n2
    expect = {(i, i): 25 for i in range(D)}
    check({k: v for k, v in left.items() if v} == expect, f'{name}: trace preservation')
    check({k: v for k, v in right.items() if v} == expect, f'{name}: unitality')
    return D


phi2 = json.loads(read_data(os.path.join(ROOT, 'two_anchor_channel.json.gz')))
phi1 = json.loads(read_data(os.path.join(ROOT, 'one_anchor_channel.json.gz')))
dims = (check_reduced(phi15, 'Phi_15', [0, 85], 786),
        check_reduced(phi2, 'Phi_2', [0, 85], 0),
        check_reduced(phi1, 'Phi_1', [0], 0))
check(dims == (32768, 31982, 31981), f'dimensions {dims}')

print('OK earlier-channel structure for Theorem 7.1')
print('baseline sha256', base)
print('relators', len(rels), 'max length', maxlen, '; all prefix walks return to the identity, no proper identity prefix')
print('original table = prefix triangles + inverse triangles; fully referenced channel: d = 44086, one singleton per label')
print('retained', len(keep), 'deleted', len(deleted), '= family (a)', fam_a, '+ family (b)', fam_b)
print('family (a) protected inverse orientation: (y,y\',1)', both, '; only (y\',y,1)', only_rev)
print('singletons of Phi_15: identity x787, witness label 85 x1; labels covered', len(covered | {0}))
print('Phi_15, Phi_2, Phi_1 (dimensions', dims, '): triangles, singletons, block pattern, padding, normalization OK')
